apiVersion: v1
kind: Service
metadata:
  name: aspecta-demo-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aspecta-demo
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
